[package]
name = "capp8_core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"

[[example]]
name = "ibm"

[[example]]
name = "chip8_logo"

[[example]]
name = "corax"

[[example]]
name = "flags"
